---
- name: Update httpd and restart if needed
  hosts: all
  become: yes

  tasks:
    - name: Update httpd package
      yum:
        name: httpd
        state: latest
      notify: Restart httpd

  handlers:
    - name: Restart httpd
      service:
        name: httpd
        state: restarted
